# 定義變量
@uri=https://jsonplaceholder.typicode.com

# 每個api用###隔開

### 使用變量

GET {{uri}}/posts/1/comments HTTP/1.1

### 新增一筆資料
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json

{
  "title": "foo",
  "body": "bar",
  "userId": 1
}

### 取得一筆資料

GET https://jsonplaceholder.typicode.com/posts/1

